version: '3'

services:

  nginx: 
    restart: always
    build:
      context: .
      dockerfile: .docker/nginx_dockerfile
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - sockets:/tmp/
      - ./odbx/static:/app/static
      - ./logs:/var/log/nginx
      - ~/keys:/keys/

  odbx:
    restart: always 
    build:
      context: .
      dockerfile: .docker/odbx_dockerfile
    environment:
      MAIN: main
      OPTIMADE_CONFIG_FILE: /app/optimade_config.json
    depends_on:
      - mongo
    volumes:
      - sockets:/tmp/
      - ./odbx/static:/app/static/
      - ./logs:/app/logs/
      - /data/structure_repository:/data/structure_repository

  mongo:
    restart: always
    build:
      context: .
      dockerfile: .docker/mongo_dockerfile
    command: ["mongod", "-f", "/etc/mongod.conf"]
    volumes:
      - sockets:/tmp/
      - ./logs:/var/logs/mongod/
      - /data/db/mongo:/data/db


volumes:
    sockets:
