version: '3'

services:

  nginx: 
    restart: always
    build:
      context: .
      dockerfile: .docker/nginx_dockerfile
      args:
        STATIC_DIR: 'odbx/static/'
    ports:
      - '8080:80'
    depends_on:
      - odbx
    volumes:
      - sockets:/tmp

  odbx:
    restart: always
    build:
      context: .
      dockerfile: .docker/odbx_dockerfile
    environment:
      MAIN: main
    depends_on:
      - mongo
    volumes:
      - sockets:/tmp

  mongo:
    restart: always
    build:
      context: .
      dockerfile: .docker/mongo_dockerfile
    volumes:
        - sockets:/tmp
        - /data/mongo/db:/data/db

volumes:
    sockets:
