name: Scheduled validator

on:
  push:
  schedule:
     - cron:  '0 */1 * * *'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: validate
      uses: ml-evs/autovalidate_optimade@master
      with: 
          host_to_validate: http://odbx.science
