name: CI

on:
  push:
  schedule:
     - cron:  '0 */1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ml-evs/autovalidate_optimade@master
      with: 
          HOST_TO_VALIDATE: http://odbx.science
