name: Remote validator

on:
  push:
  schedule:
     - cron:  '0 13 * * *'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Validate HTTPS
      uses: Materials-Consortia/optimade-validator-action@v2
      with:
        protocol: https
        domain: optimade.odbx.science
        path: /
        all versioned paths: true
        validator version: latest
        skip optional: true
    - name: Validate HTTP
      uses: Materials-Consortia/optimade-validator-action@v2
      with:
        protocol: http
        domain: optimade.odbx.science
        path: /
        all versioned paths: true
        validator version: latest
        skip optional: true
